const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');

fs.mkdirSync(distDir, { recursive: true });

// Emit a strict public declaration surface for the built entry.
// Only documented public methods on MAGEEngine are exposed (excluding #/_ internals)
// along with initMAGE.
const contents = [
  "// Auto-generated by scripts/postbuild-types.cjs",
  "// This declaration intentionally exposes only the supported public API surface.",
  "",
  "import type { MAGEEngine } from './MAGEEngine.js';",
  "",
  "export type MAGEEngineAPI = Pick<MAGEEngine,",
  "  | 'start'",
  "  | 'getAudioDuration'",
  "  | 'getAudioTime'",
  "  | 'seek'",
  "  | 'scrubAudio'",
  "  | 'play'",
  "  | 'pause'",
  "  | 'isAudioLoaded'",
  "  | 'loadAudio'",
  "  | 'loadPreset'",
  "  | 'swapCanvas'",
  "  | 'toggleFullscreen'",
  "  | 'getEngineTime'",
  "  | 'toPreset'",
  "  | 'showViewportMessage'",
  "  | 'captureFramePreview'",
  "  | 'captureThumbnail'",
  "  | 'dispose'",
  "  | 'initControls'",
  ">;",
  "",
  "export declare function initMAGE(options?: {",
  "  canvas?: HTMLCanvasElement;",
  "  log?: boolean;",
  "  withControls?: boolean;",
  "  autoStart?: boolean;",
  "}): MAGEEngineAPI;",
  "",
].join('\n');

fs.writeFileSync(path.join(distDir, 'mage-engine.d.ts'), contents, 'utf8');
