const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');

fs.mkdirSync(distDir, { recursive: true });

// Emit a strict public declaration surface for the built entry.
// Only documented public methods on MAGEEngine are exposed (excluding #/_ internals)
// along with initMAGE.
const contents = [
  "// Auto-generated by scripts/postbuild-types.cjs",
  "// This declaration intentionally exposes only the supported public API surface.",
  "",
  "export interface MAGEEngineAPI {",
  "  start(): void;",
  "  getAudioDuration(): number;",
  "  getAudioTime(): number;",
  "  seek(time: number): boolean;",
  "  scrubAudio(time: number): boolean;",
  "  play(): void;",
  "  pause(): void;",
  "  isAudioLoaded(): boolean;",
  "  loadAudio(filePath?: string): void;",
  "  loadPreset(preset: unknown): Promise<void> | void;",
  "  swapCanvas(canvas: HTMLCanvasElement): void;",
  "  toggleFullscreen(): void;",
  "  getEngineTime(): number;",
  "  toPreset(): unknown;",
  "  showViewportMessage(message: string, durationMs?: number): void;",
  "  captureFramePreview?(options?: unknown): Promise<string | null>;",
  "  captureThumbnail?(options?: unknown): Promise<string | null>;",
  "  dispose(): void;",
  "  initControls(): unknown;",
  "}",
  "",
  "export declare function initMAGE(options?: {",
  "  canvas?: HTMLCanvasElement;",
  "  log?: boolean;",
  "  withControls?: boolean;",
  "  autoStart?: boolean;",
  "}): MAGEEngineAPI;",
  "",
].join('\n');

fs.writeFileSync(path.join(distDir, 'mage-engine.d.ts'), contents, 'utf8');
