const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');

fs.mkdirSync(distDir, { recursive: true });

// Emit a strict public declaration surface for the built entry.
// Only documented public methods on MAGEEngine are exposed (excluding #/_ internals)
// along with initMAGE.
const contents = [
  "// Auto-generated by scripts/postbuild-types.cjs",
  "// This declaration intentionally exposes only the supported public API surface.",

  `/**
 * MAGEPreset represents a serializable snapshot of the MAGE engine's state, including all parameters, settings, and configurations necessary to recreate a specific visual output. It is an opaque type that can contain any data structure as long as it can be serialized and deserialized to restore the engine's state accurately.
 * The exact structure of the MAGEPreset is not defined here, as it is meant to be flexible and extensible to accommodate various use cases and future features of the MAGE engine. Users of the MAGE engine can create, save, and load presets to easily share and reproduce specific visual configurations without needing to understand the internal workings of the engine.
 * The MAGEPreset can include information such as shader parameters, audio settings, camera configurations, post-processing effects, and any other relevant data that defines the visual output of the MAGE engine at a given moment. It serves as a convenient way to capture and restore complex visual states in a single, serializable object.
 * The MAGEPreset can be used in conjunction with the loadPreset and toPreset methods of the MAGEEngineAPI to save and restore engine states, enabling users to create a library of presets for different visual styles and effects.
 */
export interface MAGEPreset {
  // The structure of the preset is not defined here, as it is considered an opaque type.
  // It can be any serializable object that represents the state of the MAGE engine.
  [key: string]: any;
}

/**
 * InputSource is an optional adapter interface for host-managed input.
 * - getState() provides an initial snapshot.
 * - subscribe(handler) streams updates and may return an unsubscribe callback.
 * This interface allows host applications to manage input state and feed it into the MAGE engine, 
 * providing greater control over input routing and handling. By implementing the InputSource interface, 
 * host applications can integrate custom input mechanisms or adapt existing ones to work seamlessly 
 * with the MAGE engine's input system.
 */
export interface InputSource {
  getState?: () => InputState;
  subscribe?: (handler: (state: InputState) => void) => void | (() => void);
}

/**
 * inputState represents externally-managed pointer and interaction signals that can be fed into the engine.
 */
export interface InputState {
  clientX?: number;
  clientY?: number;
  pointerOverUi?: boolean;
  currPointerDown?: number;
  requestWheelDirection?: -1 | 0 | 1 | number;
  requestToggleUI?: boolean;
  requestResetVisualizer?: boolean;
}

/**
 * CaptureFramePreviewOptions defines the options for capturing a single frame preview from the MAGE engine. It allows users to specify the dimensions, output format, and quality of the captured thumbnail image. The options include:
 * - width: The width of the captured thumbnail in pixels (default is 224).
 * - height: The height of the captured thumbnail in pixels (default is 224).
 * - type: The MIME type of the output image, such as 'image/png' or 'image/jpeg' (default is 'image/png').
 * - quality: The quality of the output image, a number between 0 and 1, where 1 is the highest quality (default is 0.84). This option is only applicable for lossy formats like 'image/jpeg'.
 * These options allow users to customize the appearance and format of the captured frame preview according to their needs, making it easier to generate thumbnails or snapshots of the current visual state of the MAGE engine.
 */
export interface CaptureFramePreviewOptions {
  width?: number; // Width of the captured thumbnail in pixels (default: 224)
  height?: number; // Height of the captured thumbnail in pixels (default: 224)
  type?: string; // MIME type of the output image (default: 'image/png')
  quality?: number; // Quality of the output image between 0 and 1 (default: 0.84)
}

/**
 * CaptureThumbnailOptions extends CaptureFramePreviewOptions by adding an additional option to specify the number of frames to wait for the scene to settle before capturing the thumbnail. This is useful in scenarios where the visual output may be changing rapidly, and waiting for a few frames can help ensure that the captured thumbnail represents a stable and accurate representation of the scene. The settleFrames option allows users to specify how many frames to wait before capturing, with a default value of 0, meaning that the thumbnail will be captured immediately without waiting.
 * By using CaptureThumbnailOptions, users can have more control over the timing of the thumbnail capture, ensuring that they get the best possible representation of the scene in their captured images. This can be particularly beneficial when capturing thumbnails for presets or sharing visual configurations, as it helps to avoid capturing transient or unstable visual states.
 * The CaptureThumbnailOptions can be used with the captureThumbnail method of the MAGEEngineAPI to generate thumbnails that are more representative of the intended visual output, especially in dynamic scenes where the visuals may be changing frequently.
 */
export interface CaptureThumbnailOptions extends CaptureFramePreviewOptions {
  settleFrames?: number; // Number of frames to wait for the scene to settle before capturing (default: 0)
}

/**
 * InputState represents externally-managed pointer and interaction signals that can be fed into the engine.
 * This is useful when the host application wants full control over input routing (for example React apps with layered DOM).
 * The properties of InputState include:
 * - clientX and clientY: The current pointer position in client coordinates.
 * - pointerOverUi: A boolean indicating whether the pointer is currently over the main MAGE UI element.
 * - currPointerDown: The current pointer down state, represented as a bitfield (e.g., 1 for left button, 2 for right button, etc.).
 * - requestWheelDirection: A number indicating the requested wheel scroll direction, where -1 represents scroll up, 1 represents scroll down, and 0 or undefined means no scroll.
 * - requestToggleUI: A boolean indicating whether there is a request to toggle the visibility of the MAGE UI.
 */
export interface InputState {
  clientX?: number;
  clientY?: number;
  pointerOverUi?: boolean;
  currPointerDown?: number;
  requestWheelDirection?: -1 | 0 | 1 | number;
}

/**
 * InputSource is an optional adapter interface for host-managed input.
 * - getState() provides an initial snapshot.
 * - subscribe(handler) streams updates and may return an unsubscribe callback.
 */
export interface InputSource {
  getState?: () => InputState;
  subscribe?: (handler: (state: InputState) => void) => void | (() => void);
}

/**
 * @API MAGEEngineAPI
 * @description The MAGEEngineAPI provides a set of methods for controlling the MAGE engine, including audio management, preset loading, canvas manipulation, fullscreen toggling, engine time retrieval, preset conversion, viewport messaging, frame preview and thumbnail capture, and resource disposal. It serves as the primary interface for interacting with the MAGE engine and enables users to create and manipulate visual configurations in a flexible and efficient manner.
 * @example
 * const engine = initMAGE({ canvas: myCanvas, log: true, withControls: { active: true, integrated: false }, autoStart: true });
 * engine.loadPreset(myPreset);
 * engine.play();
 * const thumbnail = await engine.captureThumbnail({ width: 128, height: 128, type: 'image/jpeg', quality: 0.9, settleFrames: 5 });
 * console.log('Captured thumbnail:', thumbnail);
 * engine.dispose();
 */
export interface MAGEEngineAPI {
  /**
   * Starts the MAGE engine, initiating the rendering loop and enabling audio playback.
   */
  start(): void;
  /**
   * Returns the total duration of the loaded audio in seconds. If no audio is loaded, it returns 0.
   */
  getAudioDuration(): number;
  /**
   * Returns the current playback time of the audio in seconds. If no audio is loaded, it returns 0.
   */
  getAudioTime(): number;
  /**
   * Seeks to a specific time in the audio playback.
   * @param time 
   */
  seek(time: number): boolean;
  /**
   * Seeks the audio playback by a specific time offset in seconds. Positive values will seek forward, while negative values will seek backward.
   * @param time 
   */
  scrubAudio(time: number): boolean;
  /**
   * Plays the audio if it is loaded and not already playing. If the audio is already playing, this method has no effect.
   */
  play(): void;
  /**
   * Pauses the audio if it is currently playing. If the audio is already paused or no audio is loaded, this method has no effect.
   */
  pause(): void;
  /**
   * Returns true if the audio is currently playing, false otherwise. If no audio is loaded, it returns false.
   */
  isAudioLoaded(): boolean;
  /**
   * Loads audio from a URL/filepath.
   * @param url 
   */
  loadAudio(url?: string): void;
  /**
   * Unloads the currently loaded audio, if any, and stops playback.
   */
  unloadAudio(): void;
  /**
   * Loads a MAGEPreset into the engine, applying all the settings and configurations contained in the preset to recreate the visual output. 
   * @param {MAGEPreset} preset - presetInput The preset to load into the engine.
   */
  loadPreset(preset: MAGEPreset): void;
  /**
   * Swaps the current rendering canvas with a new HTMLCanvasElement. This allows users to change the output canvas dynamically, which can be useful for 
   * integrating the MAGE engine into different parts of a web application or for implementing features like picture-in-picture or multi-view setups.
   * @param canvas 
   */
  swapCanvas(canvas: HTMLCanvasElement): void;
  /**
   * Toggles fullscreen mode for the MAGE engine's rendering canvas. When called, it will attempt to enter fullscreen mode if the canvas is not currently in 
   * fullscreen, or exit fullscreen mode if it is already in fullscreen.
   */
  toggleFullscreen(): void;
  /**
   * Returns the current engine time in seconds, which represents the total elapsed time since the engine was started. This can be used for synchronizing animations,
   * effects, or other time-based features within the MAGE engine. The engine time continues to advance as long as the engine is running, regardless of audio playback state.
   * @return The current engine time in seconds.
   */
  getEngineTime(): number;
  /**
   * Exports the current engine configuration as a preset object. The exported preset can include the current state, custom settings, and visualizer configuration, 
   * depending on the specified options.
   * @returns {MAGEPreset|Object} The exported preset as a MAGEPreset instance or a compact object depending on the specified schema.
   */
  toPreset(): MAGEPreset;
  /**
   * Displays a temporary message overlay on the viewport with the specified text. The message will automatically disappear after a certain duration, which can be customized by providing the durationMs parameter. This can be useful for providing feedback to users, such as confirming that a preset has been loaded, an action has been performed, or displaying any other relevant information without needing to use console logs or external UI elements.
   * @param message The text message to display on the viewport.
   * @param durationMs Optional duration in milliseconds for how long the message should be displayed before automatically disappearing. If not provided, a default duration will be used.
   */
  showViewportMessage(message: string, durationMs?: number): void;
  /**
   * Applies externally managed input state for this frame.
   * Calling this method automatically activates external input mode.
   */
  setInputState(inputState?: InputState): void;
  /**
   * Attaches an external input source adapter.
   */
  attachInputSource(inputSource?: InputSource | null): void;
  /**
   * Detaches any external input source and returns to internal window input listeners.
   */
  detachInputSource(): void;
  /**
   * Captures a single frame preview of the current visual output of the MAGE engine and returns it as a data URL string. 
   * @param options An optional object that specifies the options for capturing the frame preview, including width, height, type, and quality.
   * @return A promise that resolves to a data URL string representing the captured frame preview image, or null if the capture failed.
   */
  captureFramePreview?(options?: CaptureFramePreviewOptions): Promise<string | null>;
  /**
   * Captures a thumbnail for a MAGEPreset object using a separate MAGEEngine instance and returns the image as a data URL string.
   * @param {MAGEPreset} preset - The MAGEPreset for which to capture the thumbnail. This preset will be loaded into a temporary MAGEEngine instance to generate the thumbnail.
   * @param options - An optional object that specifies the options for capturing the thumbnail, including width, height, type, quality, and settleFrames. The settleFrames option allows waiting for a specified number of frames to ensure the scene is stable before capturing the thumbnail.
   * @return A promise that resolves to a data URL string representing the captured thumbnail image, or null if the capture failed.
   */
  captureThumbnail?(preset: MAGEPreset, options?: CaptureThumbnailOptions): Promise<string | null>;
  /**
   * Disposes of the MAGE engine instance, releasing all resources, stopping any ongoing processes, and cleaning up event listeners. 
   * After calling dispose, the engine instance should not be used anymore, and a new instance should be created if needed. 
   * This method is important for preventing memory leaks and ensuring that resources are properly released when the engine is no longer needed.
   */
  dispose(): void;
  /**
   * Initializes the tweakpane controls for the MAGE engine. This method sets up the user interface controls that 
   * allow users to interact with and modify the parameters of the MAGE engine in real-time. Also enables orbit controls for the camera,
   * allowing users to navigate the 3D scene by clicking and dragging the mouse. This method should be called after the engine has been initialized and is ready to accept user input.
   */
  initControls(): void;
  /**
   * Opens the preset dock, which is a user interface component that allows users to browse and select default MAGE presets. 
   * The preset dock is intended as a default method and is not necessarily required for all hosts. It is designed to provide
   * several examples of presets and can be used as a reference for how to implement preset browsing and selection in different
   * host applications. The implementation of the preset dock may vary depending on the specific requirements and design of the 
   * host application, and it is not a mandatory feature for all MAGE engine integrations.
   */
  openPresetDock?(): void;
}

/**
 * Initializes the MAGE engine with the specified options.
 * @param options The options for initializing the MAGE engine.
 */
export declare function initMAGE(options?: {
  canvas?: HTMLCanvasElement;
  log?: boolean;
  withControls?: { active: boolean; integrated: boolean };
  autoStart?: boolean;
}): MAGEEngineAPI;
`
].join('\n');

fs.writeFileSync(path.join(distDir, 'mage-engine.d.ts'), contents, 'utf8');